name: coding-agent
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - rust
  - pyyaml
  - requests
  - pika
  - mcp-server-fetch
  - ruff
  - pytest
  - coverage
  - pip:
      - fastmcp
      - pydantic==2.10.1
      - pydantic-settings==2.10.0
      - mcp[cli]
      - lmstudio
      - openai
      - ollama
      - portalocker
      - sqlalchemy>=2.0.0
      - psycopg2-binary>=2.9.0
      # - hashing-mcp-server
