version: 1
formatters:
  simple:
    format: '%(asctime)s %(levelname)s %(name)s %(message)s'
handlers:
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: simple
    filename: coding_agent.log
    when: midnight
    backupCount: 7
    encoding: utf8
    delay: true
    utc: false
    # 圧縮
    # Python 3.9+ で 'compression' サポート
    # compression: gzip
loggers:
  '':
    level: INFO
    handlers: [file]
    propagate: no
