mcp:
  server_url: "http://localhost:8000"
  api_key_env: "GITHUB_MCP_TOKEN"
lmstudio:
  base_url: "http://localhost:8080/v1"
  api_key_env: "LMSTUDIO_API_KEY"
github:
  owner: "my-org"
  repo: "my-repo"
  bot_label: "coding agent"
scheduling:
  interval: 300
