[tool.ruff]
line-length = 100
indent-width = 4

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D1",    # undocumented
    "TD001", # invalid todo tag
    "TD002", # missing todo author
    "TD003", # missing todo link
    "PD011", # pandas use of dot values
]
unfixable = [
    "F401", # unused import
    "F841", # unused variable
]

[tool.ruff.lint.per-file-ignores]
"tests/**" = [
    "S101",   # Use of assert detected
    "PT017",  # Found assertion on exception in except block
    "SLF001", # Private member accessed
    "PLR2004", # Magic value used in comparison
    "BLE001", # Do not catch blind exception
    "F821",   # Undefined name (common in test files)
    "F841",   # Unused variable (common in test files)
    "G004",   # Logging statement uses f-string
    "PLR0913", # Too many arguments
    "C901",   # Function is too complex
    "PLR0912", # Too many branches
    "PLR0915", # Too many statements
    "PTH118", # Use Path with / operator
    "PTH120", # Use Path.parent
    "PTH123", # Use Path.open()
    "LOG015", # Use own logger instead of root
    "D401",   # First line should be imperative mood
    "E402",   # Module level import not at top of file
    "FBT002", # Boolean default positional argument
    "E501",  # Line too long (often with translated text)
    "G201",  # Use exception() instead of error(exc_info=True)
    "ANN202", # Missing return type annotation for private function
]
